### ISSUE TITLE
Use LLMs to spellcheck/lowercase ingredient lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#297]
### What
- Use LLMs to spellcheck/lowercase ingredient lists
#### Correcting ingredient list
Can you correct the following ingredient list ? *JAMBON DE PORC (84% - ORIGINE FRANCE), *COUENNE DE PORC (9% - ORIGINE FRANCE), EAU, SEL DE MER, *SUCRE DE CANNE, #AROME NATUREL DE CITRON, #ARÔME NATUREL DE CAROUBE (PRÉSENCE NATURELLE DE POLYPHENOLS), *EXTRAIT DE LEVURE, ANTIOXYDANT: E300, #CAROTTE DÉSHYDRATÉ, *OIGNON DÉSHYDRATÉ, *POIREAU DÉSHYDRATÉ, #AIL DÉSHYDRATE, *ROMARIN DÉSHYDRATÉ, *POIVRE NOIR MOULU, AUXILIAIRE TECHNOLOGIQUE: ANTIAGGLOMÉRANT: E500,
Here is the corrected ingredient list:

*Jambon de porc (84%, origine France)
*Couenne de porc (9%, origine France)
Eau
Sel de mer
*Sucre de canne
#Arome naturel de citron
#Arôme naturel de caroube (présence naturelle de polyphénols)
*Extrait de levure
Antioxydant: E300
#Carotte déshydratée
*Oignon déshydraté
*Poireau déshydraté
#Ail déshydraté
*Romarin déshydraté
*Poivre noir moulu
Auxiliaire technologique: Antiagglomérant: E500

####  lowercase ingredient list 
Can you lowercase the following ingredient list ? *JAMBON DE PORC (84% - ORIGINE FRANCE), *COUENNE DE PORC (9% - ORIGINE FRANCE), EAU, SEL DE MER, *SUCRE DE CANNE, #AROME NATUREL DE CITRON, #ARÔME NATUREL DE CAROUBE (PRÉSENCE NATURELLE DE POLYPHENOLS), *EXTRAIT DE LEVURE, ANTIOXYDANT: E300, #CAROTTE DÉSHYDRATÉ, *OIGNON DÉSHYDRATÉ, *POIREAU DÉSHYDRATÉ, #AIL DÉSHYDRATE, *ROMARIN DÉSHYDRATÉ, *POIVRE NOIR MOULU, AUXILIAIRE TECHNOLOGIQUE: ANTIAGGLOMÉRANT: E500,
*jambon de porc (84% - origine france), *couenne de porc (9% - origine france), eau, sel de mer, *sucre de canne, #arome naturel de citron, #arôme naturel de caroube (présence naturelle de polyphenols), *extrait de levure, antioxidant: e300, #carotte déshydraté, *oignon déshydraté, *poireau déshydraté, #ail déshydraté, *romarin déshydraté, *poivre noir moulu, auxiliaire technologique: antiagglomérant: e500.

### Part of 
- #289

**Comment by raphael0202** [comment]
I've transfered from Robotoff issue #314 which is more complete.
