### ISSUE TITLE
Turn the Google cloud vision generated Python-dict stored in JSON files into actual JSONs

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#30]

**Comment by vasu-dev** [comment]
suppose we call the vision api and store the response in the response variable i.e,
 response = client.label_detection(image=image)

this returns plain protobuf objects, which can be serialized to JSON using:

from google.protobuf.json_format import MessageToJson
serialized = MessageToJson(response)

this converts the response into a JSON string, something similar to json.dumps()

and hence json.loads() methods can be used to convert it back to python dict : 
loaded_r = json.loads(serialized)

now the data can be accessed like a normal python dict.
i.e. : loaded_r['labelAnnotations'][0]['score']

Is this the issue that  you are refering to here ??
