### ISSUE TITLE
Enable whitelisting specific faces

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#37]
Many cloud computer vision have face detection algos, but they might find a face on packaging while we're looking for faces of users.
Allow to whitelist "known faces" and to flag actual faces.

**Comment by rahil1304** [comment]
Hey, I'm Rahil, I'd like to work on this issue.

**Comment by rahil1304** [comment]
Hey, I'm Rahil from India. I'd like to work on this issue.

**Comment by akshatkish** [comment]
My name is Akshat and I am from India. I would like to clarify and establish the issue, here. We require to detect faces using any face detection algorithm but then to filter out only those faces that are known to the machine learning model from training phase (which are also printed on packaging).

**Comment by rahil1304** [comment]
So finally 
1) detect the face (I'd like to use dlib and it's more accurate than voila jones and other algorithms)
2) filter out and detect only those images that are required and already known
Am I Correct?
