### ISSUE TITLE
Detect the Nutriscore on products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#38]
Some products have started displaying the ABCDE Nutriscore.
Detect that products have a Nutriscore, and which one it is.

Example: https://world.openfoodfacts.org/product/3596710467815/houmous

**Comment by llucifer97** [comment]
hi, @teolemon I would like to solve this issue.

**Comment by teolemon** [comment]
hey @llucifer97 

here are a few more details:

https://world.openfoodfacts.org/label/nutriscore.json
https://world.openfoodfacts.org/label/nutriscore
https://static.openfoodfacts.org/images/misc/nutriscore-a.svg
https://static.openfoodfacts.org/images/misc/nutriscore-b.svg
https://static.openfoodfacts.org/images/misc/nutriscore-c.svg
https://static.openfoodfacts.org/images/misc/nutriscore-d.svg
https://static.openfoodfacts.org/images/misc/nutriscore-e.svg

**Comment by llucifer97** [comment]
hi @teolemon  I have been working on the issue past 2 days. Though i am able to recognise the ABCDE SCORE but i am facing  problem in detecting the nutrisocre(a, b,c,d,e) ,I am using tensorflow object detection api , I have first made a xml file for each train image and test image and converted it to csv .AND then using those csv file iam trying to make tfrecord file .ON doing so it is throwing a error of  
: TypeError: None has type NoneType, but expected one of: int, long
googled it and i am stuck. Any advice that you could give?
