### ISSUE TITLE
Detect all mentions of carbon footprint

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#41]
![image](https://user-images.githubusercontent.com/1689815/47440778-27190580-d7af-11e8-8d8b-832d6d1f05d0.png)
Automatically detect all text mentions of carbon footprints. Probably adopt a text-based approach

**Comment by timotte1984** [comment]
avez-vous aussi les photo des côtés  de l'emballage ? car concernant l'impact carbone, on ne sait pas si c'est l'impact du produit ou d'une portion ou autre

**Comment by rishuu007** [comment]
Hey, can you provide me with the dataset(link) with the carbon footprints information over it?,
