### ISSUE TITLE
Detect country of origin automatically from label or logo

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/openfoodfacts-ai#45]
A more specific version of #7

There are two main variants of "Made in (Country)" labelling which seem common
 * Specific logos, such as "Australian Made" (see https://www.australianmade.com.au/why-buy-australian-made/about-the-logo/ for examples)
 * Wording such as "Product of" or "Made in" plus a country.

The plain text wording is likely the easiest to do; as it would be simply a pipeline looking for a country name, plus hint text; which would provide a strong indicator of country of origin.

**Comment by CloCkWeRX** [comment]
```
https://en.wiki.openfoodfacts.org/Global_labels_taxonomy

[ba12cb46f60afa5cee31f70b] /Global_labels_taxonomy InvalidArgumentException from line 107 of /var/www/off.wiki.en/extensions/mediawiki-extensions-sessionprovider-productopener-master/AuthProductOpener.body.php: Invalid user name
```
at the moment, but when its up I'll take a look!

**Comment by hrithik-jha** [comment]
Hi, I'm Hrithik and am new here. I had a question and a suggestion. For the country of origin is the aim to find out where the specific product is made or a subsidiary product of large brand made in a different location, e.g. A Hershey's chocolate has plants in Mexico, USA and other countries so are we supposed to find out where the specific chocolate bar was made or where it is made in general. If it is the latter then we can use a lexicon associating countries of production with the eatery and predict accordingly.

Sorry for the long comment.

**Comment by CloCkWeRX** [comment]
Wiki still down for me, but this seems to be working; closable?

**Comment by CloCkWeRX** [comment]
Note to self: Now lives in https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/labels.txt
