### ISSUE TITLE
Classify product based on their ingredient list, nutrition profile, and possibly more

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#5]

**Comment by aromadhony** [comment]
Hi @teolemon , I would like to take this issue. Would you like to provide more information on the class/label that should be used? Is it SENS or 5C as stated in this article https://www.anses.fr/en/content/systems-nutritional-classification-foods-comparison-sens-and-5c-based-rayners-score ?

Thank you!

**Comment by aromadhony** [comment]
I put my experimental code on automatic category classification based on ingredients in [here](https://github.com/aromadhony/GSoC2018/blob/master/OpenFoodFacts/get_cat_ingredients.ipynb)

**Comment by caldweln** [comment]
Hi @teolemon I can work on this issue....
Has the work of @aromadhony been progressed?
If not, I think I can help improve it and get something online and running.

My first question would be, what are the target categories?
I've listed the 100 most frequent categories [here](https://docs.google.com/spreadsheets/d/1fPWGpLdBIYBf6AtyL11JPae4EHe3n3ZiM3AZo_CSfo0/edit?usp=sharing), which together cover 80% of products... but I think these could be manually refined for redundancy etc.

**Comment by teolemon** [comment]
Hey @caldweln we have deployed categorization. Would you join us on Slack (https://slack.openfoodfacts.org) so that we can discuss with @raphael0202 ?
ping @teolemon once you arrive on slack :-)
