### ISSUE TITLE
Recognize labels and logos

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ai#7]
Recognize labels and logos on packaging.

NB: we have already used Google Cloud Vision to do that on part of the database. Some interesting results, but we could benefit from a more specialized solution (we have the clean images of the labels on the Wiki, but no brand dataset)

**Comment by Anubhav-Bhargava** [comment]
@teolemon  I would like to take up this issue.
I have already completed a sub part of the problem [here](https://github.com/Anubhav-Bhargava/AI-Experiments/tree/master/LOGO%20Classification)

**Comment by Anubhav-Bhargava** [comment]
Currently working on Logo localization/detection.

**Comment by Anubhav-Bhargava** [comment]
[Here](https://github.com/Anubhav-Bhargava/Logo-Classifier) is the updated Logo Classifier. It is currently trained to recognize Pepsi logo's but given enough data can be extended to other logo's also.

**Comment by ashishkumar1550** [comment]
@Anubhav-Bhargava .. Nice model there, I suggest you should try different architectures, I doubt it will work remarkable on a large scale.

**Comment by Anubhav-Bhargava** [comment]
@ashishkumar1550 Thanks for the comments. Yes, I am trying to use some advanced architectures like VGG16 or InceptionV3.

**Comment by teolemon** [comment]
We have a working game for this. Closing.
